name: ufo_2d
description: 2D UFO game.

version: 0.0.1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flame: ^0.18.0
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/images/ufo.png
    - assets/images/diamond.png
