name: ufo_2d
description: 2D UFO game.

version: 0.0.1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flame: ^0.18.0
  rxdart: ^0.23.1
  flutter:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/bg/background.png
    - assets/images/bg/floor-8x8.png
    - assets/images/static/diamond.png
    - assets/images/static/wall-metal.png
    - assets/images/ufo.png
